name: 'Upload File Action'
description: 'upload file'
author: 'Jant Hsueh(薛瑄)'
branding:
  icon: arrow-right-circle
  color: gray-dark
inputs:
  url:
    description: 'Web request URL endpoint'
    required: true
  method:
    description: 'Web request method (`GET`, `POST`, `PUT`, `PATCH`, `DELETE`)'
    required: true
    default: POST
  metadata:
    description: Data to transmit
    required: false
  upfile:
    description: File to transfer
    required: true
runs:
  using: node12
  main: index.mjs
